f1=int(input("Enter marks of student number 1 :"))
f2=int(input("Enter marks of student number 2 :"))
f3=int(input("Enter marks of student number 3 :"))
f4=int(input("Enter marks of student number 4 :"))
f5=int(input("Enter marks of student number 5 :"))
f6=int(input("Enter marks of student number 6 :"))
f7=int(input("Enter marks of student number 7 :"))
marks=[f1,f2,f3,f4,f5,f6,f7]
print(marks)
marks.sort()
print("the marks of students in asscending order is ;",marks)